name: Build Android App

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Name of the app'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set app name as env variable
        run: echo "APP_NAME=${{ inputs.app_name }}" >> $GITHUB_ENV

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: Add app name to .env
        run: echo "app_name=${{ inputs.app_name }}" >> .env

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Make gradlew executable
        run: chmod +x ./android/gradlew

      - name: Clean and Build Android APK
        run: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease

      - name: Upload APK Release - ${{ inputs.app_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.app_name }} - ${{ env.date_today }} - APK(s) release generated
          path: android/app/build/outputs/apk/release/
